#'Generate images with bounding boxes from coordinates in a dataframe
#'
#'\code{createBox} adds colored bounding boxes and labels to images based on
#'predetermined coordinates, classifiers, and image dimensions captured in a
#'dataframe.
#'
#'Load a dataframe that captures data points for each image to process.
#'The file format is the same as generated by boxer and boxer2.
#'
#'Note y-coordinates should extend downward from the top, not upward from the
#'bottom.
#'
#'@param points_master A dataframe that captures the name of the image file,
#'the four coordinates of the bounding box, the width and height dimensions
#'of the image, the classifier, and the color for the label and box. The file
#'format is a follows:
#'file_name : (chr) name of the image file;
#'x_left    : (int) left side x-coordinate;
#'y_top     : (int) top side y-coordinate;
#'x_right   : (int) right side x-coordinate;
#'y_bottom  : (int) bottom side y-coordinate;
#'size_x    : (int) image width in pixels;
#'size_y    : (int) image height in pixels;
#'classifier: (chr) classifier used as label;
#'color     : (chr) name of color to use for box and label.
#'@param file_path_input The directory that contains the image files.
#'@param file_path_output The directory where to save annotated images.
#'@param show_classifier Logical to include the classifier above the bounding.
#'box. The default is F.
#'
#'@return A new image file with the bounding box annotation for each of the
#'  images processed and resized accordingly. The name of each output image
#'  file will be the same as the corresponding input file prefixed with "out_".
#'
#' @examples
#'\dontrun{
#'points_master <- data.frame(
#'file_name = c("S2.jpg", "W1.jpg"),
#'x_left = c(43, 150),
#'y_top = c(42, 41),
#'x_right = c(526, 658),
#'y_bottom = c(595, 739),
#'size_x = c(587, 1024),
#'size_y = c(604, 768),
#'classifier = c("Skip", "Waltz"),
#'color = c("red", "yellow")
#')
#'
#'createBox(points_master = points_master, file_path_input = "/dog_pics/input/",
#'file_path_output = "/dog_pics/output/", show_classifier = T)
#'}
#'
#'@export
createBox <- function(points_master, file_path_input, file_path_output, show_classifier = F){

    # run checks to validate parameters
    checks <- c(12:15, 2:4)
    paramCheck(names = points_master$file_name, file_path_input = file_path_input, color = NA,
               outpics = T, file_path_output = file_path_output, checks = checks,
               points_master = points_master)

    for (fname in points_master$file_name){

       image <- recaptureImage(file_path_input = file_path_input, fname = fname,
                               size_x = points_master[points_master$file_name == fname,"size_x"][1],
                               size_y = points_master[points_master$file_name == fname,"size_y"][1])


       points_boxed <- points_master[points_master$file_name == fname,]



    #DRAW THE BOUNDING BOX OVER THE IMAGE AND SAVE AS OUTPUT
    if (tools::file_ext(fname) =="png"){
        grDevices::png(filename= paste0(file_path_output, "out_",fname),
                       width =  points_master[points_master$file_name == fname,"size_x"][1],
                       height = points_master[points_master$file_name == fname,"size_y"][1])

    } else if (tools::file_ext(fname) =="bmp") {
        grDevices::bmp(filename= paste0(file_path_output, "out_",fname),
                       width =  points_master[points_master$file_name == fname,"size_x"][1],
                       height = points_master[points_master$file_name == fname,"size_y"][1])

    } else {
        grDevices::jpeg(filename= paste0(file_path_output, "out_",fname),
                        width =  points_master[points_master$file_name == fname,"size_x"][1],
                        height = points_master[points_master$file_name == fname,"size_y"][1],
                        quality = 100)
    }

    graphics::plot(image)

    for (n in 1:nrow(points_boxed)){

        lab <- ifelse(show_classifier == TRUE, points_boxed$classifier[n], "")

        graphics::lines(c(points_boxed$x_left[n], points_boxed$x_left[n]),
                        c(points_boxed$size_y[n] - points_boxed$y_top[n], points_boxed$size_y[n] - points_boxed$y_bottom[n]),
                        lwd = (points_boxed$size_x[n]/360),  col = points_boxed$color[n])
        graphics::lines(c(points_boxed$x_right[n], points_boxed$x_right[n]),
                        c(points_boxed$size_y[n] - points_boxed$y_top[n], points_boxed$size_y[n] - points_boxed$y_bottom[n]),
                        lwd = (points_boxed$size_x[n]/360),  col = points_boxed$color[n])
        graphics::lines(c(points_boxed$x_left[n], points_boxed$x_right[n]),
                        c(points_boxed$size_y[n] - points_boxed$y_top[n], points_boxed$size_y[n] - points_boxed$y_top[n]),
                        lwd = (points_boxed$size_x[n]/360),  col = points_boxed$color[n])
        graphics::lines(c(points_boxed$x_left[n], points_boxed$x_right[n]),
                        c(points_boxed$size_y[n] - points_boxed$y_bottom[n], points_boxed$size_y[n] - points_boxed$y_bottom[n]),
                        lwd = (points_boxed$size_x[n]/360),  col = points_boxed$color[n])
        graphics::text(x = (points_boxed$x_left[n] + points_boxed$x_right[n])/2, y = (points_boxed$size_y[n] - points_boxed$y_top[n] + 5),
                       label = lab, col = points_boxed$color[n], cex = (points_boxed$size_x[n]/360))
    }

    grDevices::dev.off()


    }
    cat(paste0("Files created in ", file_path_output))
}



